# Generated by Django 5.0.6 on 2024-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ainame",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="authentication.ai"
            ),
        ),
    ]
