# Generated by Django 5.0.6 on 2024-09-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_userai"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai",
            name="personality",
            field=models.CharField(
                choices=[
                    ("calm", "차분함"),
                    ("active", "활발함"),
                    ("tsundere", "츤데레"),
                    ("playful", "장난꾸러기"),
                    ("mysterious", "신비로움"),
                    ("intelligent", "지적인"),
                ],
                default="calm",
                max_length=20,
            ),
        ),
    ]
