# Generated by Django 5.0.6 on 2024-09-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_ai_personality"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
