# Generated by Django 5.0.6 on 2024-11-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0006_alter_chatlog_ai_alter_userai_ai_alter_user_ainame_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userai",
            name="subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
