# Generated by Django 5.0.6 on 2024-09-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ainame", models.CharField(max_length=100, unique=True)),
                ("prompt", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "personality",
                    models.CharField(
                        choices=[
                            ("calm", "차분함"),
                            ("active", "활발함"),
                            ("tsundere", "츤데레"),
                            ("playful", "장난꾸러기"),
                            ("mysterious", "신비로움"),
                            ("intelligent", "지적인"),
                        ],
                        default="calm",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
